### ISSUE TITLE
echo validator reports error when receiving expected response code

### ISSUE THREAD

**Issue by BavoNootaert** [erasmus-without-paper/ewp-registry-service#10]
Several tests report an error like this:
Test:
Trying SecMethodCombination[HHTT] with an unsynchronized clock (Original-Date 20 minutes in the past). Expecting to receive a valid HTTP 400 error response.
Result:
IOException: Server returned HTTP response code: 400 for URL: https://qas.ewp.ugent.be/secure-api/echo

If the test is correct, the result error message should explain better what is wrong.

**Comment by wrygiel** [comment]
Confirmed. There seems to be something wrong with "catching" some kinds of responses. The code seems to turn them into exceptions, which results in an `ERROR` status (instead of a regular `SUCCESS` or `FAILURE` status).

**Comment by wrygiel** [comment]
![image](https://user-images.githubusercontent.com/2168535/32177266-2758ee7e-bd8a-11e7-9299-75e2a1f2ebe2.png)

**Comment by wrygiel** [comment]
Got it. The error occurred when the server sent a HTTP error response with empty body.

**Comment by wrygiel** [comment]
Updated. Should work now.
