### ISSUE TITLE
The registry validator does not recognize IIAS v4

### ISSUE THREAD

**Issue by ctu-developers** [erasmus-without-paper/ewp-registry-service#19]
It seems that the registry cannot detect IIAS version 4 -- https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/stable-v4

The dev-registry importer/validator for our implementation is not able to detect the IIAS GET and INDEX endpoints -- https://dev-registry.erasmuswithoutpaper.eu/manifestValidation?url=https://mobility-test.is.cvut.cz/ewp/api/manifest

If we downgrade IIAS to v3, then the IIAS endpoints will appear and pass validation to green.

I looked to coverage matrix -- https://dev-registry.erasmuswithoutpaper.eu/coverage -- and unfortunately we have probably the same problem with v4 of IIAS like "massey.edu.si" and "strato.edu.si" university. There is a note for our API -- https://dev-registry.erasmuswithoutpaper.eu/coverage#footnote-cvut.cz

Should we downgrade to v3?

**Comment by EvelienRenders** [comment]
Good question Tereza, perhaps @janinamincer-daszkiewicz can shine some light on this issue?

**Comment by janinamincer-daszkiewicz** [comment]
Do not downgrade. We are back on track and will be gradually updating the API validator (after some reorganization inside the development team). Programmers come and go, it sometimes takes time to catch up.

**Comment by ctu-developers** [comment]
Thanks for your response. I look forward to new information and changes in this ticket. [ivoš@ctu-developers]

**Comment by ctu-developers** [comment]
Hello, that was long ago resolved that?

-- https://github.com/erasmus-without-paper/ewp-registry-service/commit/62ccda7109f74f80def1ec564885adb1e8d439c1
-- https://github.com/erasmus-without-paper/ewp-registry-service/commit/d6a63ea85ac2843fed5dfd5d3c714b21be0b94d2

**Comment by mkurzydlowski** [comment]
You are right, it has been resolved!

**Comment by SimonNesvera** [comment]
As far as I could see, there still are some versions of various APIs not covered by API Validator. Namely the above mentioned IIAS 6.0.0 and 6.0.1.

**Comment by janinamincer-daszkiewicz** [comment]
It will change soon, we are just working on them

**Comment by SimonNesvera** [comment]
Thanks!

**Comment by ctu-developers** [comment]
There is new ticket  #19 for IIAs v6 ;-)
