### ISSUE TITLE
Prepare a crawling-validator for API responses

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-registry-service#2]
In Warsaw, @janinamincer-daszkiewicz proposed that WP4 might create some additional tools for testing APIs.

During the discussion, I have mentioned this it might work in a similar fashion a web-crawler does - inspecting the manifest and attempting to access all `index`-like APIs while continuously extracting entity IDs to be used as parameters for other `get`-like APIs. Such crawler would be focused on validating the responses against XSDs, but - perhaps - it might also validate some other things...?

So far, this is just an idea. We invite @erasmus-without-paper/all-members to submit ideas of their own.

**Comment by wrygiel** [comment]
I won't have time to implement this before I leave the project. This wasn't a "most wanted" feature anyway, and I don't suspect anyone would be willing to implement it. Should I leave it open?

**Comment by janinamincer-daszkiewicz** [comment]
Yes. leave it open.

**Comment by Emkas** [comment]
It's been years and the topic never came up. I'm closing it as in reality there's 0,001% chance it would be implemented.
