### ISSUE TITLE
Minor issues in local_configuration/README-local-registry.md

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-registry-service#21]
* Typo in `<enter your GitLab access token when prompted for password>` - this should read `GitHub access token`
* `repo` permission seems unneccessary - ` read:packages` seems to be all it needs
* Rename the file to `README.md` so it is displayed when someone browses the folder, instead of having to open it manually
* Clarify what the `console validator` is and how to use it. I have seen it being referred to on different occasions, but none of them seems to actually document how one would use it. If I just missed that piece of documentation, please consider linking to it here and elsewhere.

**Comment by mkurzydlowski** [comment]
> * Rename the file to `README.md` so it is displayed when someone browses the folder, instead of having to open it manually

Can you point me to the file that doesn't have the "md" extension?

> * Clarify what the `console validator` is and how to use it. I have seen it being referred to on different occasions, but none of them seems to actually document how one would use it. If I just missed that piece of documentation, please consider linking to it here and elsewhere.

We will need to get back to that.

**Comment by j-be** [comment]
> Can you point me to the file that doesn't have the "md" extension?

There is a misunderstanding. If you navigate to https://github.com/erasmus-without-paper/ewp-registry-service/tree/master/local_configuration nothing is displayed, because the file is named `README-local-registry.md`.

![image](https://user-images.githubusercontent.com/8503582/145679598-6102498f-fb2a-4ee1-a256-3eaacd2145ca.png)

If it would be named `README.md` it would be displayed, see my fork https://github.com/j-be/ewp-registry-service/tree/master/local_configuration

![image](https://user-images.githubusercontent.com/8503582/145679628-95174b2b-1b97-4841-b07c-cf7dde3a6a69.png)

**Comment by j-be** [comment]
@mkurzydlowski any news about that `console validator`?
