### ISSUE TITLE
mvn package does not seem to work

### ISSUE THREAD

**Issue by BoukeNijhuis** [erasmus-without-paper/ewp-registry-service#23]
In the README.md it says use 'mvn package' to build a jar. This does not work for me.

The errors that I get are:

[ERROR] file:/C:/git/ewp-registry-service/src/main/resources/jaxb-schemas/ewp-specs-api-omobility-las-v0.3.0/endpoints/update-request.xsd [87,105] 
org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'la:ApprovingParty' to a(n) 'type definition' component.
[ERROR] file:/C:/git/ewp-registry-service/src/main/resources/jaxb-schemas/ewp-specs-api-omobility-las-v0.3.0/endpoints/update-request.xsd [164,110] 
org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'la:ListOf_ComponentsStudied' to a(n) 'type definition' component.

The list of things I tried to fix this:

- update the schemas with the update_schemas.py script -> did not solve the problem
- removing the offending elements (as a workaround to be able to continue) -> led to new errors (see below)

I looked around the ewp-specs-api-omobility-las repository and I do see a commit where the ApprovingParty is removed:

https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/commit/7a2c1f5b57da4ad0ff2eeba8c45b0c449f572aa4

But they are still in the XSD (src/main/resources/jaxb-schemas/ewp-specs-api-omobility-las-v0.3.0/endpoints/update-request.xsd) in this project. Even after running the update script.

After removing the troubling elements I get the following error:

[ERROR] https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-types-academic-term/stable-v1/schema.xsd [129,41] 
org.xml.sax.SAXParseException: A class/interface with the same name "eu.erasmuswithoutpaper.registry.validators.types.AcademicTerm" is already in use. Use a class customization to resolve this conflict.
[ERROR] https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-types-academic-term/stable-v2/schema.xsd [128,41] 
org.xml.sax.SAXParseException: (Relevant to above error) another "AcademicTerm" is generated from here.
[ERROR] https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-types-academic-term/stable-v1/schema.xsd [129,41] 
com.sun.istack.SAXParseException2: Two declarations cause a collision in the ObjectFactory class.
[ERROR] https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-types-academic-term/stable-v2/schema.xsd [128,41] 
com.sun.istack.SAXParseException2: (Related to above error) This is the other declaration.   

So the academic-term v1 & v2 seem to clash. I was not able to fix this.

Could you please check if this works at your machine?

**Comment by mkurzydlowski** [comment]
> The errors that I get are:

```
[ERROR] file:/C:/git/ewp-registry-service/src/main/resources/jaxb-schemas/ewp-specs-api-omobility-las-v0.3.0/endpoints/update-request.xsd [87,105]
org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'la:ApprovingParty' to a(n) 'type definition' component.
[ERROR] file:/C:/git/ewp-registry-service/src/main/resources/jaxb-schemas/ewp-specs-api-omobility-las-v0.3.0/endpoints/update-request.xsd [164,110]
org.xml.sax.SAXParseException: src-resolve: Cannot resolve the name 'la:ListOf_ComponentsStudied' to a(n) 'type definition' component.
```

Everything seems fine here:

https://github.com/erasmus-without-paper/ewp-registry-service/blob/48b161361f3f75ef955e8c21b8f030df31abf8ac/src/main/resources/jaxb-schemas/ewp-specs-api-omobility-las-v0.3.0/endpoints/update-request.xsd

This schema imports:

https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-omobility-las/v0.3.0/endpoints/get-response.xsd

And the _ApprovingParty_ type is defined in that version (_v0.3.0_).

**Comment by Emkas** [comment]
@BoukeNijhuis [BoukeNijhuis](https://github.com/BoukeNijhuis) Are you still having problems with `mvn package`? I've build my forked project many times now and it works fine.

BTW. Especially if you have issues you should always add `clean`, so build it like `mvn clean package` (once something goes wrong with `package` without `clean` an issue can remain because of the first broken build)

**Comment by BoukeNijhuis** [comment]
Hi @Emkas,

I have just cloned the project (on a new laptop) and gave a 'mvn clean package'. I still get errors, but different errors now. Below the output of the second run. The first run has too much output, because of all the dependency downloading.

I think this error is caused by using a too recent java version. I used 11 & 17. This issue can be solved by added the proper libraries as far as I know.

On java 8 I get a new error which can be found at the bottom. I do not know how to solve this error.

Best regards,
Bouke

---

Java 11 & 17:
`
boukenijhuis@ocl1508388 ewp-registry-service % mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------< eu.erasmuswithoutpaper.registry:ewp-registry-service >--------
[INFO] Building ewp-registry-service 1.9.0-RELEASE
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ ewp-registry-service ---
[INFO] Deleting /Users/boukenijhuis/git/ewp-registry-service/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ ewp-registry-service ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.4:xjc (xjc) @ ewp-registry-service ---
[INFO] Created EpisodePath [/Users/boukenijhuis/git/ewp-registry-service/target/generated-sources/jaxb/META-INF/JAXB]: true
[INFO] Ignored given or default xjbSources [/Users/boukenijhuis/git/ewp-registry-service/src/main/xjb], since it is not an existent file or directory.
[INFO] Created EpisodePath [/Users/boukenijhuis/git/ewp-registry-service/target/generated-sources/jaxb/META-INF/JAXB]: true
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.421 s
[INFO] Finished at: 2022-06-08T18:56:57+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc (xjc) on project ewp-registry-service: Execution xjc of goal org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.4:xjc: javax/activation/DataSource
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:jaxb2-maven-plugin:2.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/boukenijhuis/.m2/repository/org/codehaus/mojo/jaxb2-maven-plugin/2.4/jaxb2-maven-plugin-2.4.jar
[ERROR] urls[1] = file:/Users/boukenijhuis/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar
[ERROR] urls[2] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/jaxb-core/2.3.0/jaxb-core-2.3.0.jar
[ERROR] urls[3] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/txw2/2.3.0/txw2-2.3.0.jar
[ERROR] urls[4] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.0/jaxb-runtime-2.3.0.jar
[ERROR] urls[5] = file:/Users/boukenijhuis/.m2/repository/org/jvnet/staxex/stax-ex/1.7.8/stax-ex-1.7.8.jar
[ERROR] urls[6] = file:/Users/boukenijhuis/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar
[ERROR] urls[7] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/jaxb-xjc/2.3.0/jaxb-xjc-2.3.0.jar
[ERROR] urls[8] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/xsom/2.3.0/xsom-2.3.0.jar
[ERROR] urls[9] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/codemodel/2.3.0/codemodel-2.3.0.jar
[ERROR] urls[10] = file:/Users/boukenijhuis/.m2/repository/com/sun/xml/bind/external/rngom/2.3.0/rngom-2.3.0.jar
[ERROR] urls[11] = file:/Users/boukenijhuis/.m2/repository/com/sun/xml/dtd-parser/dtd-parser/1.2/dtd-parser-1.2.jar
[ERROR] urls[12] = file:/Users/boukenijhuis/.m2/repository/com/sun/istack/istack-commons-tools/3.0.5/istack-commons-tools-3.0.5.jar
[ERROR] urls[13] = file:/Users/boukenijhuis/.m2/repository/org/apache/ant/ant/1.7.0/ant-1.7.0.jar
[ERROR] urls[14] = file:/Users/boukenijhuis/.m2/repository/org/apache/ant/ant-launcher/1.7.0/ant-launcher-1.7.0.jar
[ERROR] urls[15] = file:/Users/boukenijhuis/.m2/repository/relaxngDatatype/relaxngDatatype/20020414/relaxngDatatype-20020414.jar
[ERROR] urls[16] = file:/Users/boukenijhuis/.m2/repository/org/glassfish/jaxb/jaxb-jxc/2.3.0/jaxb-jxc-2.3.0.jar
[ERROR] urls[17] = file:/Users/boukenijhuis/.m2/repository/com/thoughtworks/qdox/qdox/2.0-M8/qdox-2.0-M8.jar
[ERROR] urls[18] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[19] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[20] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[21] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[22] = file:/Users/boukenijhuis/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[23] = file:/Users/boukenijhuis/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[24] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[25] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[26] = file:/Users/boukenijhuis/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.5.1/maven-plugin-annotations-3.5.1.jar
[ERROR] urls[27] = file:/Users/boukenijhuis/.m2/repository/org/apache/maven/skins/maven-fluido-skin/1.6/maven-fluido-skin-1.6.jar
[ERROR] urls[28] = file:/Users/boukenijhuis/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
[ERROR] urls[29] = file:/Users/boukenijhuis/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar
[ERROR] urls[30] = file:/Users/boukenijhuis/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[31] = file:/Users/boukenijhuis/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.5/istack-commons-runtime-3.0.5.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : javax.activation.DataSource
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
`

Java 8:
`
/Users/boukenijhuis/Library/Java/JavaVirtualMachines/liberica-1.8.0_333/bin/java -Dmaven.multiModuleProjectDirectory=/Users/boukenijhuis/git/ewp-registry-service -Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=60484:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2022.1.1 clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------< eu.erasmuswithoutpaper.registry:ewp-registry-service >--------
[INFO] Building ewp-registry-service 1.9.0-RELEASE
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ ewp-registry-service ---
[INFO] Deleting /Users/boukenijhuis/git/ewp-registry-service/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (validate) @ ewp-registry-service ---
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- jaxb2-maven-plugin:2.4:xjc (xjc) @ ewp-registry-service ---
[INFO] Created EpisodePath [/Users/boukenijhuis/git/ewp-registry-service/target/generated-sources/jaxb/META-INF/JAXB]: true
[INFO] Ignored given or default xjbSources [/Users/boukenijhuis/git/ewp-registry-service/src/main/xjb], since it is not an existent file or directory.
[INFO] Created EpisodePath [/Users/boukenijhuis/git/ewp-registry-service/target/generated-sources/jaxb/META-INF/JAXB]: true
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install-node-and-npm) @ ewp-registry-service ---
[INFO] Installing node version v8.11.1
[INFO] Downloading https://nodejs.org/dist/v8.11.1/node-v8.11.1-darwin-arm64.tar.gz to /Users/boukenijhuis/.m2/repository/com/github/eirslett/node/8.11.1/node-8.11.1-darwin-arm64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.358 s
[INFO] Finished at: 2022-06-08T18:59:16+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install-node-and-npm) on project ewp-registry-service: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1
`

**Comment by Emkas** [comment]
First of all this is kind of bigger project, so as far as my experience go, it won't work on JDK >= 11 without changes. Project is set on JDK 1.8 and I'd try to stick on it.

Second thing is, the Internet tells me that `Could not download Node.js: Got error code 404 from the server.` is because of old version of `frontend-maven-plugin` (https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/m1-mac-cant-build-wknd-tutorial-get-quot-could-not-download-node/m-p/399462). Try to alternate `pom.xml` (line 425) and change `frontend-maven-plugin` version from 1.6 to e.g. 1.12.1 (the newest one at the moment).

**Comment by Emkas** [comment]
OK. I created a pull request to fix this. So that we could close this issue.
