### ISSUE TITLE
Extremely long response times, sometimes even timeout

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-registry-service#24]
Recently, we started noticing weird failures in API validation. We initially couldn't find much in the logs, until we noticed that https://registry.erasmuswithoutpaper.eu/catalogue-v1.xml sometimes take extremely long to answer (4 minutes and more), rarely even timing out after 5 minutes. It seems to me these timeouts are not taken into account when calculating "Uptime ratios" [here](https://registry.erasmuswithoutpaper.eu).

The validation check though seems to time out much earlier, causing failures on our side reported as timeouts. We do cache the Catalogue for one hour (if we are able to fetch one), but we have not (yet) implemented a fallback to "keep stale copy".

I also see that both types of caches are optional ("clients SHOULD cache the registry" and "Clients MAY keep the stale copy" [here](https://github.com/erasmus-without-paper/ewp-specs-api-registry)).

From all of this (some of this is speculation, as it is extremely difficult to debug):

* Timeout of the automatic validation seems to be shorter than the timeout on https://registry.erasmuswithoutpaper.eu/catalogue-v1.xml, which makes little sense to me.
* If catalogue is down/unreachable, an error in the validation is not the HEI's implementation's fault since all countermeasures (aka. caching) are optional. Any such failure should imho. not be reported (see "The boy who cried wolf").
* I'd like to see recommendations for timeouts. In detail: we are currently running 60 seconds timeouts on our load-balancer. It seems the validation times out earlier (else the `SocketException: Read timed out` reported to us makes little sense), while the Catalogue API times out after 5 minutes, which seems extremely high.

**Comment by janinamincer-daszkiewicz** [comment]
We are looking into the problem.

**Comment by janinamincer-daszkiewicz** [comment]
The problem has been solved months ago.
