### ISSUE TITLE
generated jaxb sources fails validation

### ISSUE THREAD

**Issue by kneringerjohann** [erasmus-without-paper/ewp-registry-service#25]
Dear EWP Team,

we want to use jaxb generated classes within a jdk 13 springboot project.

We are able to generate the classes, but the XML Validation fails (https://dev-registry.erasmuswithoutpaper.eu/schemaValidator)

Our XML looks like this:

`<institutions-response xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-institutions/tree/stable-v2">
  <hei>
    <hei-id>fh-kufstein.ac.at</hei-id>
    <name xml:lang="en">University of Applied Sciences Kufstein</name>
    <wstxns1:street-address xmlns:wstxns1="https://github.com/erasmus-without-paper/ewp-specs-types-address/tree/stable-v1">
      <recipientName xmlns="">Mag. John Doe Fachhochschule Kufstein Tirol Bildungs GmbH</recipientName>
      <addressLine xmlns="">Andreas Hofer Strasse 7</addressLine>
      <postalCode xmlns="">6330</postalCode>
      <locality xmlns="">Kufstein</locality>
      <region xmlns="">Tyrol</region>
      <country xmlns="">AT</country>
    </wstxns1:street-address>
    <wstxns2:mailing-address xmlns:wstxns2="https://github.com/erasmus-without-paper/ewp-specs-types-address/tree/stable-v1">
      <recipientName xmlns="">Mag. John Doe Fachhochschule Kufstein Tirol Bildungs GmbH</recipientName>
      <addressLine xmlns="">Andreas Hofer Strasse 7</addressLine>
      <postalCode xmlns="">6330</postalCode>
      <locality xmlns="">Kufstein</locality>
      <region xmlns="">Tyrol</region>
      <country xmlns="">AT</country>
    </wstxns2:mailing-address>
    <website-url>https://www.fh-kufstein.ac.at</website-url>
    <logo-url>https://www.fh-kufstein.ac.at/bundles/styleflasherfhkufstein/images/redesign-20yrs/logo.svg</logo-url>
    <mobility-factsheet-url xml:lang="en">https://www.fh-kufstein.ac.at/eng/study/international/incoming-students/ects-guide</mobility-factsheet-url>
    <course-catalogue-url xml:lang="en">https://www.fh-kufstein.ac.at/eng/study/international/incoming-students/International-Program</course-catalogue-url>
    <course-catalogue-url xml:lang="en">https://www.fh-kufstein.ac.at/eng/study/international/incoming-students/Winter-Semester-Courses</course-catalogue-url>
    <course-catalogue-url xml:lang="en">https://www.fh-kufstein.ac.at/eng/study/international/incoming-students/Summer-Semester-Courses</course-catalogue-url>
    <wstxns3:contact xmlns:wstxns3="https://github.com/erasmus-without-paper/ewp-specs-types-contact/tree/stable-v1">
      <contact-name xmlns="">Mag. John Doe</contact-name>
      <person-given-names xmlns="">John</person-given-names>
      <person-family-name xmlns="">Doe</person-family-name>
      <wstxns4:phone-number xmlns:wstxns4="https://github.com/erasmus-without-paper/ewp-specs-types-phonenumber/tree/stable-v1">
        <e164 xmlns="">+43537276666666666666</e164>
      </wstxns4:phone-number>
      <email xmlns="">John.Doe@fh-kufstein.ac.at</email>
      <wstxns5:street-address xmlns:wstxns5="https://github.com/erasmus-without-paper/ewp-specs-types-address/tree/stable-v1">
        <recipientName xmlns="">Mag. John Doe Fachhochschule Kufstein Tirol Bildungs GmbH</recipientName>
        <addressLine xmlns="">Andreas Hofer Strasse 7</addressLine>
        <postalCode xmlns="">6330</postalCode>
        <locality xmlns="">Kufstein</locality>
        <region xmlns="">Tyrol</region>
        <country xmlns="">AT</country>
      </wstxns5:street-address>
    </wstxns3:contact>
  </hei>
</institutions-response>
`

Anyone else facing this problems with jaxb?
We generate the classes with jdk1.8 with the xjc goal.

thank you in advance

**Comment by kneringerjohann** [comment]
[xml_fhu.txt](https://github.com/erasmus-without-paper/ewp-registry-service/files/6953124/xml_fhu.txt)

**Comment by kneringerjohann** [comment]
Edit: This is not related to the JDK Version, I did built my project with JDK 1.8, same XML File with those issues!

**Comment by mkurzydlowski** [comment]
Are you referring to errors in the street-address element caused by the lack of namespace (xmlns = "")?

I'm not really able to tell you why JAXB generated it that way. We don't face the same problem in our implementation that also uses JAXB.

**Comment by kneringerjohann** [comment]
> Are you referring to errors in the street-address element caused by the lack of namespace (xmlns = "")?
> 
> I'm not really able to tell you why JAXB generated it that way. We don't face the same problem in our implementation that also uses JAXB.

Yes, this is one problem.
Another problem is that the namespace prefixes are not used on their childs in the street adress (wstxns1).

**Comment by Emkas** [comment]
@kneringerjohann Did you managed to overcome this issue? If not please show us your jaxb configuration in gradle/maven etc.

**Comment by Emkas** [comment]
I'll assume that everything is fine now. We're building `jaxb2-maven-plugin:2.5.0:xjc` in our every build in CI. Now with Java 11. There should be no problems on newer version, but I'd recommend using TLS versions of Java anyway.
