### ISSUE TITLE
The registry validator does not recognize IIAS v6

### ISSUE THREAD

**Issue by ctu-developers** [erasmus-without-paper/ewp-registry-service#26]
It seems that the registry cannot detect IIAS version 6 -- https://github.com/erasmus-without-paper/ewp-specs-api-iias/tree/stable-v6

It's the same bug like #19 (https://github.com/erasmus-without-paper/ewp-registry-service/commit/d6a63ea85ac2843fed5dfd5d3c714b21be0b94d2) without coverage matrix problem ;-)

Thank you for resolving the issue.

**Comment by mkurzydlowski** [comment]
I have updated the validator to take into account IIAs v6.
