### ISSUE TITLE
Validator bad HTTP-Date format

### ISSUE THREAD

**Issue by madiken21** [erasmus-without-paper/ewp-registry-service#28]
According to [MDN Web Docs](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Date), day part of HTTP-Date must be on 2 digits, but validator do a request with only 1 digit.

ex : 
Date: Tue, 2 Nov 2021 13:46:47 GMT

![image](https://user-images.githubusercontent.com/69417420/139864449-65135089-d1e4-4fee-8add-79d56eccdf51.png)

The problem is that the webserver (IIS) gives a Date header with a 2 digits day, in respect with RFC1123, so httpsignature validation fails.

What is the correct expected behavior ?

**Comment by mkurzydlowski** [comment]
You are right that RFC 1123 date format should be used in the validator:
https://datatracker.ietf.org/doc/html/rfc2616#section-3.3.1

Even though the format with a single digit day must be parsed by servers, still the validator should use the 2 digit format.

**Comment by Emkas** [comment]
This is a known issue with RFC_1123 date format (e.g. https://stackoverflow.com/questions/7707555/getting-date-in-http-format-in-java). I'll try to create a pull request with a fix.

**Comment by Emkas** [comment]
I'll look into it, but this one should be fixed long time ago.

**Comment by Emkas** [comment]
As of 1.11.0 this is fixed for sure. But is was fixed around 2022.
