### ISSUE TITLE
The registry validator does not recognize TORs v2

### ISSUE THREAD

**Issue by ctu-developers** [erasmus-without-paper/ewp-registry-service#38]
It seems that the registry cannot detect TORs version 2 -- https://github.com/erasmus-without-paper/ewp-specs-api-imobility-tors/tree/v2.0.0

Because of this, it is not possible to perform tests for version 2, but only for version 1 of TORs.

The dev-registry importer/validator is not able to detect new version of the TORs GET and INDEX endpoints -- https://dev-registry.erasmuswithoutpaper.eu/manifestValidation?url=https://mobility-test.is.cvut.cz/ewp/api/manifest

It's the same bug like https://github.com/erasmus-without-paper/ewp-registry-service/issues/19 and https://github.com/erasmus-without-paper/ewp-registry-service/issues/26 ;-)

Thank you for resolving the issue.

**Comment by ctu-developers** [comment]
Please label this ticket as BUG. Tickets #19 and #26 too. Thanks.

**Comment by Emkas** [comment]
As mentioned here: https://github.com/erasmus-without-paper/ewp-registry-service/commit/7d5ab328471320086af24b760780ac247f2d8972#commitcomment-80716455
This seems to be resolved.
