### ISSUE TITLE
Can't connect to docker.pck.github.com

### ISSUE THREAD

**Issue by glaurentiu** [erasmus-without-paper/ewp-registry-service#45]
Error response from daemon: Get "https://docker.pck.github.com/v2/": x509: certificate is valid for *.github.com, www.github.com, github.io, github.com, *.github.io, githubusercontent.com, *.githubusercontent.com, not docker.pck.github.com

Does anyone have this problem?

**Comment by Emkas** [comment]
Maybe this was a temporary issue. I've just login/logout without any issues and I was able to download latest image.
