### ISSUE TITLE
Redundant tests on <max-omobility-codes>

### ISSUE THREAD

**Issue by ctu-developers** [erasmus-without-paper/ewp-registry-service#46]
There is redundant (and wrong) test on \<max-omobility-codes\> paramaters for OMobs/GET, OMob LAs/GET, IMobs/GET and IMob TORs/GET endpoints. These endpoints do not have the \<max-omobility-codes\> parameter.

<img src="https://user-images.githubusercontent.com/8960573/183646820-f2e94ccf-16e9-450e-8674-196a93d78404.png" width="640">

<img src="https://user-images.githubusercontent.com/8960573/183646848-f218b085-b62e-4120-8b1c-e5fa1d90240d.png" width="640">

<img src="https://user-images.githubusercontent.com/8960573/183646909-c206da44-70b2-48d3-a467-87260a929ad5.png" width="640">

**Comment by Emkas** [comment]
Thank you very much for reporting an issue in Aug 2022, of a bug fixed in Nov 2021 and released (officially!) i Jun 2022. Release date, with fancy number, doesn't mean that running applications in prod/dev had this bug until that date.
