### ISSUE TITLE
XML Schema Validator should not pretty-print before validation

### ISSUE THREAD

**Issue by geostarling** [erasmus-without-paper/ewp-registry-service#65]
Hi,

with one in-house provider we analyse a problem with their EWP API (IIA CNR API). It is returning responses that are not valid according to XML Schema.

I wanted to provide evidence to the partner, so I run the XML through the XML Schema Validator that is part of the EWP Registry. To my surprise, however, the validator marked the response as OK which is contradictory to the result provided by other reference XSD validator utilities.

Specifically, this is the XML returned by the partner:

```
<iia-cnr-response
    xmlns="https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr/tree/stable-v2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd
        https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-architecture/stable-v1/common-types.xsd
    ">
</iia-cnr-response>
```

The problem rests with the end-line character inside `<iia-cnr-response>` element, which is inconsistent with the [XSD specification](https://github.com/erasmus-without-paper/ewp-specs-api-iia-cnr/blob/81516dc4b38486e54fbd2e5a161825dd9d776444/response.xsd#L25).

This issue is detected by other XSD validators (confirmed by Xerces-J-based validator and IntelliJ IDEA) :

![validation1](https://github.com/erasmus-without-paper/ewp-registry-service/assets/210511/7548f8b9-7549-4a83-8521-a8244d94c66e)

but not by the EWP Registry XSD Validator:

![validation2](https://github.com/erasmus-without-paper/ewp-registry-service/assets/210511/8d21e468-b9a0-40fe-80ec-ec85d98b066b)

I looked for possible reasons why the validation passes in the EWP Registry and found out that the XML Schema Validator in the Registry performs [pretty-print reformatting of the XML input first](https://github.com/erasmus-without-paper/ewp-registry-service/blob/master/src/main/java/eu/erasmuswithoutpaper/registry/documentbuilder/EwpDocBuilder.java#L207) (which in this case supposedly removes the end-line) and after that it [runs XSD validation](https://github.com/erasmus-without-paper/ewp-registry-service/blob/6d7da1ee7dd5c240dab45f14cac0eaed1d2c2048/src/main/java/eu/erasmuswithoutpaper/registry/documentbuilder/EwpDocBuilder.java#L239) on the pretty-printed XML and not on the original.

The pretty printing before validation does not seem to me like a correct thing to do.

(Also please note, that the [`input.isMakingPretty()`](https://github.com/erasmus-without-paper/ewp-registry-service/blob/6d7da1ee7dd5c240dab45f14cac0eaed1d2c2048/src/main/java/eu/erasmuswithoutpaper/registry/documentbuilder/EwpDocBuilder.java#L205) seems to be always [set to true](https://github.com/erasmus-without-paper/ewp-registry-service/blob/6d7da1ee7dd5c240dab45f14cac0eaed1d2c2048/src/main/java/eu/erasmuswithoutpaper/registry/web/UiController.java#L535) )

**Comment by Emkas** [comment]
It look like your diagnosis is right. We've applied a fix.

Thank you for this bug report!
