### ISSUE TITLE
Explicitly include a non-versioned API in dev-registry

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-registry-service#8]
We want our Registry to be compatible with non-EWP APIs. We even stated that on the Developers page:

> We are designing our Registry in a way that should allow it to be of use in other EU projects too. If you are developing such a project, consider using our Registry Service by hosting the Discovery Manifest file compatible with our specifications.

However, I'm afraid that some clients might have missed [this one crucial part of the specification](https://github.com/erasmus-without-paper/ewp-specs-api-registry/blob/v1.3.0/catalogue.xsd#L289):

> We encourage you to include non-EWP-related APIs too, if you think that other partners in the EWP Network might make use of them! It is RECOMMENDED **(but NOT strictly required)** that all such API descriptions extend the `ApiEntry` complexType defined in common-types.xsd schema

For example, some clients might have assumed that all API entries will always have the `version` attribute, which is not required by the above specs. (All EWP APIs will, but some others might not.)

In order to detect this mistake, I propose to include a fake API entry in the dev-registry - one which doesn't have the `version` attribute.

**Comment by janinamincer-daszkiewicz** [comment]
> Does this mean that we can have HEIs not interested in Erasmus exchanges, but entitled to query our APIs, just because they are in the registry, even if without an<institutions-covered>element?

It is possible, although the probability is low.
In particular, the EMREX network may withdraw from the EWP Registry in the future (some work has started in that direction).

> Currently I see they have only a certificate, but could they have an RSA-Public Key, if they decide so?

The Registry does not restrict manifest files in that respect.
