### ISSUE TITLE
echo validator complains about key not covering het echo endpoint

### ISSUE THREAD

**Issue by BavoNootaert** [erasmus-without-paper/ewp-registry-service#9]
For ugent.be we get the following error:
Test:
Trying SecMethodCombination[AHTT] (no client authentication). Expecting a valid HTTP 401 or HTTP 403 error response.
Error message:
The keyId extracted from the response's Signature header has been found in the Registry, but it doesn't cover the Echo API endpoint which has generated the response. Make sure that you have included your key in a proper manifest section.

However, according to de 'details', the keyId is the one that appears in the registry. There is only one key for ugent.be.

**Comment by wrygiel** [comment]
Your key (`00680e3df119f7af17674423d61742c08d1eb9e6959f9a0f20142250a655dd44`) is present only in the `<client-credentials-in-use>` section (see [here](https://github.com/erasmus-without-paper/ewp-registry-log-dev/blob/b3c4aef9b843d1024883872183e573c698630cce/catalogue-v1.xml#L901)), so it can be used only for making requests. If you want the same key to also be used for signing responses, then you must include it also in the `<server-credentials-in-use>` section.

**Comment by BavoNootaert** [comment]
Indeed, that solved the problem.
